#! /bin/sh

# Start up script for bspwm
# launch default theme 
# Write system status check WITH log HERE!!!
# rofi theme selection
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf &
pgrep -x dunst > /dev/null || dunst &
pkill polybar && $HOME/.config/polybar/T-1/launch.sh &

# Settings:

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false


bspc rule -a firefox desktop='^2' state=monocle

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"





